name: Sign iOS Shortcut

on:
  workflow_dispatch:
    inputs:
      shortcut_data:
        description: 'Base64 encoded shortcut plist data'
        required: true
        type: string
      shortcut_name:
        description: 'Name of the shortcut'
        required: true
        type: string
      callback_url:
        description: 'Optional callback URL for completion notification'
        required: false
        type: string

jobs:
  sign-shortcut:
    runs-on: self-hosted
    
    steps:
    - name: Sign Shortcut (Ultra Fast)
      run: |
        echo "🚀 Starting ultra-fast shortcut signing..."
        echo "📝 Shortcut name: ${{ github.event.inputs.shortcut_name }}"
        
        # Create temp directory and files
        TEMP_DIR=$(mktemp -d)
        SHORTCUT_FILE="$TEMP_DIR/${{ github.event.inputs.shortcut_name }}.shortcut"
        SIGNED_FILE="$TEMP_DIR/${{ github.event.inputs.shortcut_name }}_signed.shortcut"
        
        # Decode and validate in one command
        echo "${{ github.event.inputs.shortcut_data }}" | base64 -d > "$SHORTCUT_FILE"
        
        # Quick validation and signing
        if plutil -lint "$SHORTCUT_FILE" > /dev/null 2>&1 && \
           shortcuts sign --mode anyone --input "$SHORTCUT_FILE" --output "$SIGNED_FILE"; then
          echo "✅ Shortcut signed successfully ($(stat -f%z "$SIGNED_FILE") bytes)"
          echo "SIGNED_FILE=$SIGNED_FILE" >> $GITHUB_ENV
        else
          echo "❌ Shortcut signing failed"
          exit 1
        fi
        
    - name: Upload Signed Shortcut
      uses: actions/upload-artifact@v4
      with:
        name: signed-shortcut-${{ github.run_id }}
        path: ${{ env.SIGNED_FILE }}
        retention-days: 1
        
    - name: Notify Completion
      if: github.event.inputs.callback_url != ''
      run: |
        curl -X POST "${{ github.event.inputs.callback_url }}" \
          -H "Content-Type: application/json" \
          -d "{
            \"status\": \"success\",
            \"run_id\": \"${{ github.run_id }}\",
            \"shortcut_name\": \"${{ github.event.inputs.shortcut_name }}\",
            \"download_url\": \"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
          }" 