name: Sign iOS Shortcut

on:
  workflow_dispatch:
    inputs:
      shortcut_data:
        description: 'Base64 encoded shortcut plist data'
        required: true
        type: string
      shortcut_name:
        description: 'Name of the shortcut'
        required: true
        type: string
      request_id:
        description: 'Unique request identifier for concurrency safety'
        required: true
        type: string
      callback_url:
        description: 'Optional callback URL for completion notification'
        required: false
        type: string

jobs:
  sign-shortcut:
    runs-on: self-hosted
    
    steps:
    - name: Sign Shortcut (Concurrency Safe)
      run: |
        echo "🚀 Starting concurrency-safe shortcut signing..."
        echo "📝 Shortcut name: ${{ github.event.inputs.shortcut_name }}"
        echo "🆔 Request ID: ${{ github.event.inputs.request_id }}"
        
        # Sanitize shortcut name for filename (remove emojis and special chars)
        SANITIZED_NAME=$(echo "${{ github.event.inputs.shortcut_name }}" | sed 's/[^a-zA-Z0-9 ._-]//g' | sed 's/  */ /g' | xargs)
        echo "🧹 Sanitized filename: $SANITIZED_NAME"
        
        # 🔧 FIX #1: Create request-specific temp directory to prevent collisions
        REQUEST_ID="${{ github.event.inputs.request_id }}"
        TEMP_DIR=$(mktemp -d -t "shortcut-${REQUEST_ID}-XXXXXX")
        SHORTCUT_FILE="$TEMP_DIR/input.shortcut"
        SIGNED_FILE="$TEMP_DIR/${SANITIZED_NAME}.shortcut"
        
        echo "🔍 Working in request-specific directory: $TEMP_DIR"
        echo "🔍 Request ID: $REQUEST_ID"
        
        # Decode and validate shortcut data
        echo "${{ github.event.inputs.shortcut_data }}" | base64 -d > "$SHORTCUT_FILE"
        
        # 🔍 VALIDATION: Check shortcut content matches request
        echo "🔍 Validating shortcut content..."
        if command -v plutil >/dev/null 2>&1; then
          SHORTCUT_NAME_IN_PLIST=$(plutil -extract WFWorkflowName raw "$SHORTCUT_FILE" 2>/dev/null || echo "Unknown")
          echo "📋 Shortcut name in plist: '$SHORTCUT_NAME_IN_PLIST'"
          echo "📋 Expected name pattern: '${{ github.event.inputs.shortcut_name }}'"
        fi
        
        # Sign the shortcut
        if plutil -lint "$SHORTCUT_FILE" > /dev/null 2>&1; then
          echo "✅ Shortcut plist is valid"
          echo "🔐 Signing shortcut..."
          
          # Clear temp directory of any existing signed files
          find "$TEMP_DIR" -name "*.shortcut" -not -name "input.shortcut" -delete 2>/dev/null || true
          
          if shortcuts sign --mode anyone --input "$SHORTCUT_FILE" --output "$TEMP_DIR/signed.shortcut"; then
            echo "✅ Shortcut signing command completed"
            
            # Find the actual signed file (shortcuts CLI might create different name)
            ACTUAL_SIGNED=$(find "$TEMP_DIR" -name "*.shortcut" -not -name "input.shortcut" | head -n 1)
            
            if [ -f "$ACTUAL_SIGNED" ]; then
              # Ensure proper filename for download
              if [ "$ACTUAL_SIGNED" != "$SIGNED_FILE" ]; then
                mv "$ACTUAL_SIGNED" "$SIGNED_FILE"
                echo "📝 Renamed to: $(basename "$SIGNED_FILE")"
              fi
              
              echo "✅ Shortcut signed successfully ($(stat -f%z "$SIGNED_FILE") bytes)"
              echo "🔍 Final file: $(basename "$SIGNED_FILE")"
              echo "🔍 Request ID: $REQUEST_ID"
              echo "SIGNED_FILE=$SIGNED_FILE" >> $GITHUB_ENV
              echo "SIGNED_FILE_NAME=$(basename "$SIGNED_FILE")" >> $GITHUB_ENV
              echo "REQUEST_ID=$REQUEST_ID" >> $GITHUB_ENV
            else
              echo "❌ Could not find signed shortcut file in $TEMP_DIR"
              echo "📁 Directory contents:"
              ls -la "$TEMP_DIR"
              exit 1
            fi
          else
            echo "❌ Shortcut signing command failed"
            exit 1
          fi
        else
          echo "❌ Invalid shortcut plist format"
          exit 1
        fi
        
    - name: Upload Signed Shortcut (Request-Specific)
      uses: actions/upload-artifact@v4
      with:
        name: signed-shortcut-${{ env.REQUEST_ID }}-${{ github.run_id }}
        path: ${{ env.SIGNED_FILE }}
        retention-days: 1
      if: env.SIGNED_FILE != ''
        
    # 🔧 CONCURRENCY SAFETY: Each request gets unique artifact name with request_id
    # This prevents wrong shortcut assignment in concurrent scenarios
